export const GET_CURRENCIES = 'crypto/GET_CURRENCIES';
export const GET_CURRENCIES_SUCCESS = 'crypto/GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_ERROR = 'crypto/GET_CURRENCIES_ERROR';
export const FETCH_CURRENCY = 'crypto/FETCH_CURRENCY';
export const FETCH_CURRENCY_SUCCESS = 'crypto/FETCH_CURRENCY_SUCCESS';
export const FETCH_CURRENCY_ERROR = 'crypto/FETCH_CURRENCY_ERROR';
export const FILTER_CURRENCIES = 'crypto/FILTER_CURRENCIES';
export const FILTER_CURRENCIES_SUCCESS = 'crypto/FILTER_CURRENCIES_SUCCESS';

