export const GET_CURRENCIES = 'crypto/GET_CURRENCIES';
export const GET_CURRENCIES_SUCCESS = 'crypto/GET_CURRENCIES_SUCCESS';
export const GET_CURRENCIES_ERROR = 'crypto/GET_CURRENCIES_ERROR';
export const FILTER_CURRENCIES = 'crypto/FILTER_CURRENCIES';
export const FILTER_CURRENCIES_SUCCESS = 'crypto/FILTER_CURRENCIES_SUCCESS';

